# Generated by Django 5.1 on 2024-08-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('highlight1', models.TextField()),
                ('highlight2', models.TextField()),
                ('highlight3', models.TextField()),
                ('highlight4', models.TextField()),
                ('highlight5', models.TextField()),
                ('highlight6', models.TextField()),
            ],
        ),
    ]
