# Generated by Django 5.1 on 2024-08-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectlong_projectshort_delete_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlong',
            name='url',
            field=models.URLField(),
        ),
    ]
