# Generated by Django 5.1 on 2024-08-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectlong_highlight1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlong',
            name='highlight1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='projectlong',
            name='highlight2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='projectlong',
            name='highlight3',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='projectlong',
            name='highlight4',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='projectlong',
            name='highlight5',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
