# Generated by Django 5.1 on 2024-08-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('aboutme', models.TextField()),
                ('linkedinurl', models.CharField(max_length=200)),
                ('githuburl', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('certgot', models.CharField(max_length=150)),
                ('expir', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Coreskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=150)),
                ('major', models.CharField(max_length=150)),
                ('minor', models.CharField(max_length=150)),
                ('startyear', models.CharField(max_length=200)),
                ('stopyear', models.CharField(max_length=200)),
            ],
        ),
    ]
