# Generated by Django 5.1 on 2024-08-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workexperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('highlight1', models.CharField(blank=True, max_length=150)),
                ('highlight2', models.CharField(blank=True, max_length=150)),
                ('highlight3', models.CharField(blank=True, max_length=150)),
                ('highlight4', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
