# Generated by Django 5.1 on 2024-08-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='endy',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='starty',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
