# Generated by Django 5.1 on 2024-08-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_workexperience_endy_workexperience_starty'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
